force-app/main/default/objects/Opportunity/fields/Custo_estimado__c.field-meta.xml
<CustomField>
    <fullName>Custo_estimado__c</fullName>
    <label>Custo estimado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Data_Fim__c.field-meta.xml
<CustomField>
    <fullName>Data_Fim__c</fullName>
    <label>Data Fim</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Data_Inicio__c.field-meta.xml
<CustomField>
    <fullName>Data_Inicio__c</fullName>
    <label>Data Início</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tecnologia_do_Projeto__c.field-meta.xml
<CustomField>
    <fullName>Tecnologia_do_Projeto__c</fullName>
    <label>Tecnologia do Projeto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Salesforce</fullName>
            </value>
            <value>
                <fullName>SAP</fullName>
            </value>
            <value>
                <fullName>JavaScript</fullName>
            </value>
            <value>
                <fullName>C#</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Tempo_Estimado__c.field-meta.xml
<CustomField>
    <fullName>Tempo_Estimado__c</fullName>
    <description>Em semanas</description>
    <inlineHelpText>Tempo estimado em Semanas</inlineHelpText>
    <label>Tempo Estimado</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Opportunity/fields/Valor_da_proposta__c.field-meta.xml
<CustomField>
    <fullName>Valor_da_proposta__c</fullName>
    <label>Valor da proposta</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/classes/PropostaOpportunityPDFController.cls
public with sharing class PropostaOpportunityPDFController {

    public Opportunity opp { get; set; }

    public PropostaOpportunityPDFController() {

        Id oppId = ApexPages.currentPage().getParameters().get('id');

        if (oppId == null) {
            return;
        }

        opp = [
            SELECT
                Id,
                Name,
                Account.Name,
                Tecnologia_do_Projeto__c,
                Tempo_Estimado__c,
                Data_Inicio__c,
                Data_Fim__c,
                Custo_Estimado__c,
                Valor_da_proposta__c
            FROM Opportunity
            WHERE Id = :oppId
        ];
    }
}